config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources "contacts", only: [:new, :create]
  get 'contact' => 'contacts#new'
  post 'contact' => 'contacts#create'

  root "pages#home"

  get "skills" => "pages#skills"
  get "history" => "pages#history"
  get "education" => "pages#education"
  get "interests" => "pages#interests"
  get "references" => "pages#references"
  get "contact" => "pages#contact"
  get "mpd" => "pages#mpd"

end

app/models/contact.rb
class Contact < MailForm::Base
  include MailForm::Delivery
  
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "MyCV Contact Form",
      :to => "ashamywilson1991@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
    @contact = Contact.new(params[:contact])  
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. I will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def skills
  end

  def history
  end

  def education
  end

  def interests
  end

  def references
  end

  def contact
  end

  def mpd
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<!-- Wrap all page content here -->
<div class="navbar-wrapper">
  <div class="container">
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="dropdown">
            <a href="#" class="navbar-brand dropdown-toggle" data-toggle="dropdown">Ashleigh's Résumé <span class="glyphicon glyphicon-thumbs-up"></span></a>
            <ul class="dropdown-menu">
              <%= render_shareable :buttons=> [ 'facebook' ] %>
              <li class="divider"></li>
            </ul>
          </div>
        </div>
        
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to root_path do %>
                <span class="glyphicon glyphicon-home"></span> Home
              <% end %>
            </li>
            <li>
              <%= link_to contact_path do %>
                <span class="glyphicon glyphicon-envelope"></span> Email
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-duplicate"></span> My CV<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My skills", skills_path %></li>
                <li><%= link_to "Work history", history_path %></li>
                <li><%= link_to "My education", education_path %></li>
                <li><%= link_to "Interests & hobbies", interests_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Referees / references", references_path %></li>
              </ul>
            </li>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
</div>

app/views/pages/education.html.erb
<div id="primary-content">
	<div class="container-pages">
		<hr class="featurette-divider">
		<div id="flip-element">
			<h1>My Secondary | Education</h1>
		</div>
		<hr class="featurette-divider">
		<div class="container-images">
			<div id="zoom-content">
				<img src="https://pbs.twimg.com/profile_images/1431452276/newlogo_400x400.jpg" class="img-responsive2" alt="Ashleigh Wilson School">
			</div>
		</div>
		
		<div id="bounce-right">
			<div class="top edu col2"><b>It is my pleasure to introduce you to Westland High School.</b></p></div>
			<div class="row">
  			<div class="col-md-8"><p class="beta-p left">Westland High School Hokitika is a Years 7 to 13 co-educational, multi-course secondary school serving the area from Chesterfield in the north to Waitaha in the south.</p> 
				<p class="beta-p left">Students enjoy the advantage of smaller classes and a friendly family like atmosphere where they are treated as individuals and their talents are recognised and built on.</p>
				<p class="beta-p left">My favourite subjects were English, Technology, Social Sciences & The Arts.</p></div>
  			<div class="col-md-4 top"><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11725.315385471933!2d170.973305!3d-42.71793!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x837a0c7a0b2740aa!2sWestland+High+School!5e0!3m2!1sen!2snz!4v1425452335914" width="100%"height="200" frameborder="2" style="border:0"></iframe></div>
			</div>
		</div>
		<div id="bounceleft-content">
			<div class="row">
				<div class="col-md-8 top1"><p class="beta-p soc2"><b><i>Westland Social Links</i></b></p>
					<p>
						<a href="https://www.facebook.com/WestlandHigh" target="_blank">
   					<%= image_tag("icon_facebook_tiny.png", alt: "facebook") %></a>
   					<a href="https://twitter.com/westlandhigh" target="_blank">
   					<%= image_tag("icon_twitter_tiny.png", alt: "twitter") %></a>			
   				</p>
   			</div>
			</div>
		</div>
		<hr class="featurette-divider">
		<p class="beta-p">For all questions regarding my  <a><%= link_to "Education", contact_path %></a> shoot me a message.</p>		
	</div>
</div>

app/views/pages/history.html.erb
<div id="primary-content">
	<div class="container-pages">
		
		<div id="zoom-content">
			<h1>My Employment | 2012 - 2015</h1>
		</div>
		
		
		<div id="bounceleft-content">
			<hr class="featurette-divider">
			<div class="row">
  			<div class="col-md-4 soc1 hob1">
  				<div class="container-images">
  					<img src="http://staticblog.virtualvocations.com/2013/01/ID-10059857.jpg" class="img-responsive" alt="Ashleigh Wilson">
  				</div>
  				<p class="beta-p"><a><%= link_to "Wanted, Hire me!", contact_path %></a></p>
  			</div>
  			<div class="col-md-8 top"><p class="beta-p left">The past 3 years i have been full-time care giver for Miss Sylvia Rowe. Over this period Sylvia & i lived together in the garden City of Christchurch New Zealand. Sylvia's a lovely lady with a kind heart, family minded & she was also a career woman of 35 years with a general retail goods department store. She always had an old tale to tell about work mates or the days-gone-by she spent on her mums dariy farm.</p> 
				<p class="beta-p left">Miss Rowe sure had her fair share of lifes troubles, in her latter years she suffered from many serious medical issues including arthritis, crippling her mobitity & dementia which causes brain disease. But despite all, & with a little help, Sylvia Rowe kept her cheery positive outlook on life.</p>
				<p class="beta-p left">Unfortunately Miss Rowe's life was taken early 2015 due to kidney failure. She will allways hold a special place in my heart, she is dearly missed by me & her family.<i> Sylvia Rowe 1940 - 2015.</i></p></div>
			</div>
		</div>
		<div id="bounce-right">
			<div class="row">
				<div class="col-md-8 top"><p class="soc1 col">Job discription was ..</p>
					<p class="beta-p left">
						My responsibilities included general home up-keep like dusting, hoovering, washing clothes, making her bed, cooking most meals, and feeding the cat. Sylvia's personal hygiene was also taken care of by me which entailed help showering & dressing. Spending time with her just having a good old chat over a cup of tea.
   				</p>
   				<p class="beta-p left">
						It was also my job to arrange any appointments Miss Rowe may need like the hairdresser, doctor or dentist and provide transportation. Medication was also administered by me, arranging pick up of prescription and administer blister-pac's at scheduled times.
   				</p>
   				<p class="beta-p left">
						Miss Rowe was under Enduring Power of Attorney while in my care, all of her main financial affairs were managed by the Public Trust Government Offices NZ. However Sylvia did have a petty-cash account. On her behalf it was my job to manage her usage / exspenditure<i> 'every day items'</i>  she may require.  
   				</p>	
   			</div>
				<div class="col-md-4 top1 pad">
					<p class="beta-p"><i>Miss Sylvia Rowe</i></p>
					<div class="container-images">
						<img src="https://s3.amazonaws.com/ashleighwilson.me/Picture0080.jpg" class="img-responsive1" alt="Sylvia Rowe">
					</div>
				</div>
			</div>
			<hr class="featurette-divider">
			<p class="beta-p">For all questions regarding my <a><%= link_to "Employment", contact_path %></a> history shoot me a message.</p>					
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div id="primary-content">
	<div class="container-pages-home">
		<div id="flip-element">
			<h1 class="title-name"> Hey, I'm Ashleigh Wilson</h1>
		</div>
		<hr class="featurette-divider">
		<div id="bounce-right">
			<p class="lead">Personal Statement</p>
			<p class="beta-p">Inspiring 23 year old girl with a tenacious drive to learn new skill sets.</p>
			<p class="beta-p">Seeking to begin a new career after dedicating the last 3 years of my life to home caregiving.</p>
		</div>
		
		<div class="container-image-home">
			<div id="zoom-content">
				<img src="https://pbs.twimg.com/profile_images/572237802746548224/GaWI6vpY_400x400.jpeg" class="img-responsive2" alt="Ashleigh Wilson">
			</div>
		</div>
		
		<div id="bounceleft-content">
			<h4>My Employment goal</h4>
			<p><i>find work in ..</i></p>
			<div class="home-goal">
				<h1 class="homegoal-text">Rest home caregiving | Home caregiving.</h1>
			</div>
			<p class="beta-p">I would prefer to work in a rest home, but will consider all job offers.</p>
		</div>
		<hr class="featurette-divider">
		<%= image_tag("personal.png", alt: " Ashleigh Wilson personal details") %> 
		<p class="beta-p">I am located in Christchurch New Zealand.</p>
		<p class="beta-p">
			<i>For all other personal details including my home address, phone, email, & mobile</i> <a><%= link_to "please contact me here", contact_path %></a>. 
   	</p>
		<p class="beta-p">My Social links</p>
		<p>
			<button type="button" class="btn btn-info" aria-label="Left Align" data-toggle="tooltip" data-placement="left" title="Add me !"><a href="https://www.facebook.com/Ash19910/" target="_blank"><%= image_tag("icon_facebook_tiny.png", alt: "Ashleigh Wilson facebook") %></a></button> 
			
			<button type="button" class="btn btn-info" aria-label="Left Align" data-toggle="tooltip" data-placement="right" title="Follow me !"><a href="https://twitter.com/ashleighamywils" target="_blank"><%= image_tag("icon_twitter_tiny.png", alt: "Ashleigh Wilson twitter") %></a></button>			
		</p>
		<hr class="featurette-divider">
		<div class="home-instruc">
			<p> Check out the rest of my awesome CV by clicking <b><i> "My CV"</i></b> above.</p>
		</div>		
	</div>
</div>

app/views/pages/interests.html.erb
<div id="primary-content">
	<div class="container-pages">
		
		<div id="flip-element">
			<h1>My | interests & hobbies</h1>
			<p>Hey all here's what i like to do when i'm not at work ..</p>
		</div>
		
		
		<div id="bounce-content">
			<div class="slow-content">
				<hr class="featurette-divider">

				<div class="row skills">
  				<div class="col-md-4 top">
  					<div class="container-images">
  						<img src="https://cheap.buyessay.org/blog/wp-content/uploads/2014/07/Shopping-Girls-Vector-Illustration.jpg" class="img-responsive" alt="Ashleigh Wilson interests">
  					</div>
  				</div>
			
  				<div class="col-md-8 top">
  					<p class="beta-p left">I love shopping ! What girl doesn't like an out-going to the shopping mall with mates, i certainly do and it's at least a once a week thing for me.</p> 
						<p class="beta-p left">Spending time with family is important to me. I guess i'm a bit of a mummy's girl and i love my dad too. It's always fun just swapping stories & seeing what everybody has been up-to.</p>
						<p class="beta-p left">I can also be a bit of an online social media hog, facebook get's quite a bit of my time as there is always some fresh gossip to spread around.</p>
					</div>
				</div>
		
				<div class="row skills">
  				<div class="container-images-rgt">
  					<span>
  						<img src="http://cvsteps.com/wp-content/uploads/e-learning.jpg" class="img-responsive" alt="Ashleigh Wilson hobbies">
  					</span>
  				</div>
  				

  				<div class="col-md-8">
  					<span class="e-text">
  						<p class="beta-p left top">I enjoy learning new skills through educational tutorial's mainly online. Everything from 'cosmetic videos' to creating that tasty recipe for the family to tech-tutorial's.</p> 
							<p class="beta-p left">There is always something new & interesting to learn online.</p>
							<p class="beta-p left">Currently i'm following Tom Hopkins, he has an array of awesome sales tutorial videos. If you haven't seen him in action i highly recommend taking a look if your in sales. His methods can be applied weather your in real estate or retail sales. Go on <a href="https://youtu.be/vZa29V2L-U4" target="_blank"><i>click here</i></a> to view How To Master The Art Of Selling Anything on YouTube.</p>
						</span>
  				</div>
				</div>

				<div class="row">
					<div class="col-md-4">
  					<div class="container-images">
  						<img src="http://cdn.geekmonkey.org/series/avatars/000/000/007/original/ruby-on-rails.png?1345813329" class="img-responsive" alt="Ashleigh Wilson interests">
  					</div>
					</div>
  				<div class="col-md-8 top">
  					<p class="beta-p left">I particularly love tagging along with a best mate of mine that's currently studying web-based application development ( building websites ).</p> 
						<p class="beta-p left">He is learning Ruby on Rails4 which is a bit over my head, but by just spending time with him i've picked up quite a few skills in basic html & some css which i'm getting pretty good at.</p>
						<p class="beta-p left">I helped out with some of the css in this site !</p>
  				</div>
				</div>

				<hr class="featurette-divider">
				<div class="row skills">
					<div class="container-images-rgt">
						<span>
							<img src="http://www.wired.com/images_blogs/autopia/images/2008/08/19/qantas_2.jpg" class="img-responsive" alt="Ashleigh Wilson travel">
						</span>
					</div>
					<div class="col-md-8">
						<span class="e-text">
   						<p class="beta-p left">My family & i have traveled extensively through Australia between 2006 - 2008. It was awesome ! i most definitely would like to rome-around some more sometime in the future.</p>
   						<p class="beta-p left">I have always wanted to visit Dubai, there are more than seventy shopping malls there, as well as countless numbers of more traditional retail outlets. I will be sure not to miss visiting the Ibn Battuta Mall. Named after a legendary traveller. As well as retail outlets, it also contains a wide variety of entertainment facilities and food and drink establishments. Yay !</p>
   						<p class="beta-p left">I have included a video of my family & me on our Australia trip below. Hope you like ..</p>
   					</span>
   				</div>
				</div>
				
				<iframe width="100%" height="315" src="https://www.youtube.com/embed/v4ko8CCSVok?rel=0&amp;controls=0" frameborder="0"></iframe>
				<hr class="featurette-divider">
				<p class="beta-p">For all questions regarding my <a><%= link_to "interests & hobbies", contact_path %></a>  shoot me a message.</p>
			</div>
		</div>
	</div>
</div>

app/views/pages/mpd.html.erb
<div class="mpd">
  <div class="jumbotron">
    <div id="primary-content">
      <h1><strong>Congratulations</strong></h1>
    </div>
    <div id="zoom-content">
      <h2> you have just found your next <strong>top employee </strong>!</h2>
    </div>
    <p><a class="btn btn-lg btn-default fa fa-2x fa-sort-desc" href="#faster" role="button"></a></p>
  </div>

  <a name="faster"></a>

  <div class="container containerStandard">      
    <div class="row beta-p">
      <%= image_tag("personal.png", alt: " Ashleigh Wilson personal details") %>
      <h2>I'm <strong>Ashleigh Wilson Mpd's</strong> next top rep to be.</h2>
      <p class="beta-p">You want to <strong>hire me</strong> because i am . . .</p>
    </div>                
  </div>
  <hr>
        
  <div class="container containerStandard">
    <div class="row">      
      <div class="col-md-4 columnItem">
        <img class="img-circle" src="http://www.partidiricambi.com/wp-content/uploads/2015/03/truth-and-lies-300x300.jpg">
        <h2>Honest</h2>
        <p class="beta-p">Within all my relationships business and personal <strong>honesty</strong> is important to me. As you probably already know, that simple act of being honest builds strong relationships and compiled with time creates a good track record. I think it's important to tell as much truth as you can, it's petty much just common sence i guess.</p>
      </div>

      <div class="col-md-4 columnItem">
        <img class="img-circle" src="http://identitymagazine.net/wp-content/uploads/2011/02/passion_for_life.jpg">
        <h2>Passion</h2>
        <p class="beta-p">I've always wanted to work with people just like <strong>You !</strong> I'm very interested in improveing my sales skills and keen to get my training under-way. A real satisfaction comes from selling a great product or promoting a good service, it's just rewarding when at the end of it all, you have a happy client or customer.</p>
      </div>

      <div class="col-md-4 columnItem">
        <img class="img-circle" src="http://chrissy50.files.wordpress.com/2012/08/yesorno-300x300.jpg?w=625">
        <h2>Adaptable</h2>
        <p class="beta-p">If anyone has the ability to change oneself to fit to occuring change it's me ! To be honest with you i love a bit of change and hey where would we all be with out it. A world without change ? it's food for thought.. I guess in someway we all are  <strong>adaptible.</strong> What more is there to say, hire me! and teach me! lets change.</p>
      </div>
    </div>
  </div>
        
  <div class="container screenshot">   
    <div class="arrow-down"></div>
    <div class="col-md-5">
      <div class="screenBlurb">
        <hr>

        <h1>Simple Fast & Intuitive</h1>                    
        <p class="beta-p">Sort of a funny story. My partner and i have what we like to call our <strong>"forward plan"</strong> the plan is simple, we regularly set a new goal each and give it a deadline. ( Mine is currently <i>'to find employment within the sales market'</i> ) Once our goals are decided we put them on paper and then we go get shit done ! It's not a race or a compitition with us, but it's a partnership or team effort that goes on between us, in that we support and help each other acheive and keep each other on track. </p>
        <p class="beta-p">Ok maybe thats not a funny story, it's most definitly a pretty cool story. The reason i shared this with you is because it holds relavance to my success if say for example i was employed by you. I'm giving you a peek into my family life so you can get better picture of what sort of people we are. Now with all that said i can continue on and you'll understand where i'm coming from.</p>                            
        <p class="beta-p">I learn fast and have a good family support structure at home. My partner of 7 years is always ready to help out with my personal development.</p>
        <p class="beta-p">With my tenatious drive, my wonderful partners support, and your training i'm sure i will be able to easily gain the skills required to become a successful rep of Mpd.</p>

        <h4 class="title-name">I'm, Ashleigh Wilson.</h2>
        <hr>
      </div>
    </div>
    <div class="col-md-7 screen">
      <img class="img-screenshot" src="https://media.licdn.com/mpr/mpr/p/5/005/08d/393/249f54f.jpg">                
    </div>
  </div>
        
  <div class="container containerStandard">
    <div class="row">
      <div class="col-md-12"><h2>Stuff i like about you Mpd</h2></div>
    </div>
    <div class="row">   
      <div class="col-md-4 columnItem"><h3><i class="fa fa-university"></i><BR>Established</h3>
        <p class="beta-p">Your history sounds great, it's awesome that you guys have been in business for over a decade. This means to me job security and peace of mind.</p>
      </div>
      <div class="col-md-4 columnItem"><h3><i class="fa fa-group"></i><BR>Diversity</h3>
        <p class="beta-p">My research on you showed that Mpd has clients in all sorts of industry. This sounds good to me as it means that working with you  should be interesting from day to day.</p>
      </div>      
      <div class="col-md-4 columnItem"><h3><i class="fa fa-lightbulb-o"></i><BR>Smart Business</h3>
        <p class="beta-p">Your international relationship with Appco group is a helper in my eyes. It's handy to have support to call upon when needed.</p>
      </div>
    </div>
                    
    <div class="row">   
      <div class="col-md-4 columnItem"><h3><i class="fa fa-graduation-cap"></i><BR>Training</h3>
        <p class="beta-p">Education is key to me. My online resources have been ok, but what i really need is to be apart of a pro - sales team and learn through practical field experience. I am super keen to get started as soon as i can.</p>
      </div>
      <div class="col-md-4 columnItem"><h3><i class="fa fa-gavel"></i><BR>Work Ethic</h3>
        <p class="beta-p">I think it's a really good thing you guys have included 'good work ethic' into your business values. Hey it maybe something to do with your success ? Being honest, as you should know by now certainly works for me.</p>
      </div>
      <div class="col-md-4 columnItem"><h3><i class="fa fa-money"></i><BR>Enterpeneurial</h3>
        <p class="beta-p">Currently running my own business is a scary prospect. I guess what i'm trying to say here is maybe with the help of Mpd that will change in the future. Even though at the moment i'm not that enterpeneurial it will sure be good for me to be around those that are that way !</p>
      </div>
    </div>          
  </div>
      
  <div class="container containerStandard platform">
    <div class="arrow-down"></div>
    <div class="row">
      <h2><strong><a><%= link_to "Hire Me !", contact_path %></a></strong> Mpd group lets..</h2>
    </div>
            
    <div class="row">
      <div class="col-sm-4 columnItem">
        <h3><i class="fa fa-5x fa-youtube-play"></i></h3>
        <h3>Get => Started</h3>
      </div>
      <div class="col-sm-4 columnItem">
        <h3><i class="fa fa-5x fa-line-chart"></i></h3>
        <h3>PromoteGoodBusiness</h3>
      </div>
      <div class="col-sm-4 columnItem">
        <h3><i class="fa fa-5x fa-trophy"></i></h3>
        <h3>Succeed ~ together !</h3>
      </div>
    </div>
  </div>
</div>

app/views/pages/references.html.erb
<div id="primary-content">
	<div class="container-pages">
		<h1>Referees | references</h1>
		<hr class="featurette-divider">
		<div class="container-image-home">
			<div id="bounce-right">
				<img src="http://lonelybrand.com/blog/wp-content/uploads/2012/08/customer-reference.png" class="img-responsive" alt="Ashleigh Wilson referees">
			</div>
		</div>
		<hr class="featurette-divider">
		<div id="zoom-content">
			<p class="ref">Available on request, <a><%= link_to "click here", contact_path %></a>  to shoot me a message.</p>
		</div>
		<hr class="featurette-divider">
		<div id="lightspeed2">
			<h3 class="title-name sign">Ashleigh Wilson.</h3>
		</div>
	</div>
</div>

app/views/pages/skills.html.erb
<div id="primary-content">
	<div class="container-pages">
		
		<div id="flip-element">
			<h1>Ashleigh Wilson | Skills</h1>
		</div>
		
		<div id="bounce-content">
			<div class="slow-content">
				<hr class="featurette-divider">

				<div class="row skills">
  				<div class="col-md-4 top">
  					<div class="container-images">
  						<img src="http://jumpstart-hr.com/wp-content/uploads/2013/09/effective-communication-480x300.jpg" class="img-responsive" alt="Ashleigh Wilson skills">
  					</div>
  				</div>
			
  				<div class="col-md-8"><p class="soc1 col">Communication skills</p>
  					<p class="beta-p left">Able to communicate well with most people within most circumstances. Over the years i've traveled extensively through Australia and  meet many diverse cultures. From my experiences i have gained '<i>awesome communication </i>' skills.</p> 
						<p class="beta-p left">I also have a good mannerism and i'm very well spoken with an reasonable vocabulary.</p>
						<p class="beta-p left">I'm as i like to put it, <i> quite an experiance on the phone</i> and i'm told i sound pretty good too, and obviously i'm good at chatting with our elderly.</p>
					</div>
				</div>

				<div class="row skills">
  				<div class="container-images-rgt">
  					<span>
  						<img src="http://www.callcentrehelper.com/images/stories/2010/2013/01/missing-skills-5103.gif" class="img-responsive" alt="Ashleigh Wilson skills">
  					</span>
  				</div>
  				<div class="col-md-8"><p class="soc1 col">Numeracy skills</p>
  					<span class="e-text">
  						<p class="beta-p left">In 2008 i was part-time employed with a popular cafe / coffee shop in Australia's Goldcoast, i gained practical retail experience including cash register skills.</p> 
							<p class="beta-p left">While caring for Miss Rowe i developed good budgeting skills and conducted ethical management of her petty-cash-account. This included a written weekly budget projection, accruals, retain all transaction receipts for regular audit by Miss Rowes attorney.</p>
							<p class="beta-p left">Good over-all money handling skills.</p>
						</span>
  				</div>
				</div>

				<div class="row skills">
					<div class="col-md-4 top">
  					<div class="container-images">
  						<img src="https://tunxis.digication.com/files/M01f37ba327dcdf8b82a01de6a24f1afd.jpg" class="img-responsive" alt="Ashleigh Wilson skills">
  					</div>
					</div>
  				<div class="col-md-8"><p class="soc1 col">Teamwork skills</p>
  					<p class="beta-p left">Ability to integrate into new team environments, with my easy going helpful nature theirs not much to dislike.</p>
						<p class="beta-p left">I love to learn new skills and pick-up things fast with usually very minimal instruction. I'm also always keen to help out the team where i can.</p>
						<p class="beta-p left">I would make a valuable asset for your business team.</p>
  				</div>
				</div>
		
				<div class="row skills top">
					<div class="container-images-rgt">
						<span>
							<img src="http://cdn.skilledup.com/wp-content/uploads/2014/10/Learn-Business-Administration-Online-2-Feature_1290x688_KL.jpg" class="img-responsive" alt="Ashleigh Wilson skills">
						</span>
					</div>
					<div class="col-md-8 adm"><p class="soc1 col">Administration skills</p>
						<span class="e-text">
							<p class="beta-p left">Reasonable computer basics skills, abiliy to execute every-day tasks ( OSX / Windows ).</p>
   						<p class="beta-p left">Good at coordinating my daily tasks and others if required.</p>
   						<p class="beta-p left">Basic book-keeping experience.</p>
   						<p class="beta-p left">Able to work supervised / un-supervised and get the job done.</p>
   					</span>
   				</div>
				</div>
				<hr class="featurette-divider">
				<p class="beta-p">
					For all questions regarding my <a><%= link_to "Skills", contact_path %></a> shoot me a message. 
   			</p>
			</div>
		</div>
	</div>
</div>